require("module-alias/register");
const Koa = require("koa");
const parser = require("koa-bodyparser");
const InitManager = require("./core/init");
const catchError = require("./middlewares/exception");
const static = require("koa-static");
const path = require("path");
require("./app/models/user");
const app = new Koa();
app.use(catchError);
app.use(parser());
app.use(static(path.join(__dirname, "static/images")));
InitManager.initCore(app);
app.listen(3000, () => console.log("server is starting, port 3000...."));
